#ifndef LINEAR_DEPTH_GRADIENT_H
#define LINEAR_DEPTH_GRADIENT_H

#include "../Common/HLSLCompat.h"

#define LINEAR_DEPTH_GRAD_THREAD_GROUP_SIZE_X 8
#define LINEAR_DEPTH_GRAD_THREAD_GROUP_SIZE_Y 8
#define LINEAR_DEPTH_GRAD_THREAD_GROUP_SIZE_Z 1

struct cbLinearDepthGrad
{
	uint_ OutputDescHeapIdx;
};

#endif // LINEAR_DEPTH_GRADIENT_H