#ifndef SKY_DI_PARAMS_H
#define SKY_DI_PARAMS_H

#define MAX_PLANE_DIST_REUSE 0.01
#define MIN_NORMAL_SIMILARITY_REUSE 0.906307787    // within 25 degrees
#define MAX_ROUGHNESS_DIFF_REUSE 0.1f
#define NUM_SPATIAL_SAMPLES 2
#define SPATIAL_SEARCH_RADIUS 16
#define APPROXIMATE_EMISSIVE_SHADOW_RAY 1

#endif